### ISSUE TITLE
[BUG] PAPER-143 , AFKHunger 1.1.2

### ISSUE THREAD

**Issue by JustKing009** [Galaxyzd/Galaxy-AFKHunger#1]
I Have die WARN in my Logs, can you fix it please?
[18:34:07] [Server thread/WARN]: [Abbys-AFKHunger] Task #521 for Abbys-AFKHunger v1.1.2 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1428) ~[?:?]
	at com.abbydiode.afkhunger.timers.AFKTimer$1.run(AFKTimer.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-143]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-143]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-143]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-143]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-143]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-143]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-143]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by abbydiode** [comment]
Could you please give more information about how to reproduce this issue?

**Comment by JustKing009** [comment]
I have reproduce the message. if op player give other player creative .
